=== aaronleechan/CS157BXML/directory.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="person_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="gender">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="person" type="person_type"/>
    <xs:complexType name="directory_type">
        <xs:sequence>
            <xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="directory" type="directory_type"/>
</xs:schema>

=== aaronleechan/CS157BXML/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<directory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="directory.xsd">
    <person gender="male">
        <name>Ayesha Malik</name>
        <email>amalik@sjsu.edu</email>
    </person>
    <person gender="male">
        <name>Sean Sullivan</name>
        <email>ssullivan@mac.com</email>
    </person>
    <person gender="female">
        <name>Mary Jane</name>
        <email>mjane@google.com</email>
    </person>
    <person gender="male">
        <name> Naveen Balani </name>
        <email>nblani@yahoo.com</email>
    </person>
</directory>
